#!/bin/bash
# author : maxime déraspe
# email : maximilien1er@gmail.com
#

date=$(date +%Y-%m-%d)

DIR=$(dirname "$(readlink -f $0)")

if [[ $1 == "" ]];then
    echo -e "Need at least one database to download !\n"
    echo " microbe-dbs.sh database output"
    echo "    databases :"
    echo "       refseq_bacteria           RefSeq bacteria from NCBI ftp"
    echo "       refseq_plasmid            RefSeq plasmid from NCBI ftp"
    echo ""
    exit 0
else
	  case "$1" in
	      refseq_bacteria)
		        $DIR/db-scripts/refseq.sh $2 "bacteria" ;;
        refseq_plasmid)
		        $DIR/db-scripts/refseq.sh $2 "plasmid" ;;
        refseq_viral)
		        $DIR/db-scripts/refseq.sh $2 "viral" ;;
	      g)
		        genome=1
		        ;;
	      f)
		        phages=1
		        ;;
	      p)
		        plasmid=1
		        ;;
        b)
		        blast=1
		        ;;
        h)
            echo " microbe-dbs.sh database output"
            echo "    databases :"
            echo "       refseq_bacteria           RefSeq bacteria from NCBI ftp"
            echo "       refseq_plasmid            RefSeq plasmid from NCBI ftp"
            echo "       refseq_viral              RefSeq virus from NCBI ftp"
            echo ""
		        ;;
        \?)
		        echo "Invalid Database !"
		        exit 0
		        ;;
	  esac
fi
