#!/bin/bash
# author : maxime déraspe
# email : maximilien1er@gmail.com
#

date=$(date +%Y-%m-%d)

DIR=$(dirname "$(readlink -f $0)")

cli_help=$(cat << EOF

     microbe-dbs.sh database output
        databases :
           refseq_bacteria           RefSeq bacteria from NCBI ftp
           refseq_plasmid            RefSeq plasmid from NCBI ftp
           refseq_viral              RefSeq viral from NCBI ftp
           refseq_archaea            RefSeq archaea from NCBI ftp

           vfdb                      Virulence Factor Database
           mibig                     Minimum Information about a Biosynthetic Gene cluster

EOF
        )

if [[ $1 == "" ]]; then
    echo "Need at least 1 databases !!"
    echo "$cli_help"
    exit 0
else
    if [ -z $2 ]; then
        output="$1"
    else
        output=$2
    fi
    case "$1" in
        refseq_bacteria)
            $DIR/db-scripts/refseq.sh $output "bacteria"
            ;;
        refseq_plasmid)
            $DIR/db-scripts/refseq.sh $output "plasmid"
            ;;
        refseq_viral)
            $DIR/db-scripts/refseq.sh $output "viral"
            ;;
        refseq_archaea)
            $DIR/db-scripts/refseq.sh $output "archaea"
            ;;
        vfdb)
            $DIR/db-scripts/vfdb.sh $output
            ;;
        mibig)
            $DIR/db-scripts/mibig.sh $output
            ;;
        help)
            echo "$cli_help"
		        ;;
        \?)
		        echo "Invalid Database !"
		        exit 0
		        ;;
    esac
fi
